version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  qrtoolkit:
    build: .
    networks:
      - app
    ports:
      - '8090'
    environment:
      - SECRET_KEY=12345678
      - ALLOWED_HOSTS=qrtoolkit.local.itkdev.dk
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/src:/home/snake/src:delegated
      - ${PWD}/static:/var/www/qrtoolkit/static:delegated

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - qrtoolkit
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/static:/var/www/qrtoolkit/static:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
