version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  qrtoolkit:
    build: .
    networks:
      - app
    ports:
      - '8090'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/src:/home/snake/src
      - ${PWD}/static:/var/www/qrtoolkit/static

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - qrtoolkit
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/static:/var/www/qrtoolkit/static
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
