when:
  - event: release

skip_clone: true

steps:
  - name: Ansible playbook
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: host
      path:
        from_secret: path
      user:
        from_secret: user
      playbook: 'release'
      pre_up:
        - itkdev-docker-compose-server build --no-cache
        - itkdev-docker-compose-server run --rm --user snake qrtoolkit python manage.py collectstatic
        - itkdev-docker-compose-server run --rm --user snake qrtoolkit python manage.py migrate
